services:
  # Interface Homme-Machine en HTML/CSS/JS/PHP
  ihm:
    build: ./ihm
    volumes:
      - ./ihm:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
    ports:
      - "8080:80"
    networks:
      - calc_net

  # Calculateur en Python
  calc:
    build: ./calc
    volumes:
      - ./calc/src:/usr/src/app/src
    ports:
      - "8081:80"
    networks:
      - calc_net

  # Interface BDD en C#
  int_db:
    image: int_db
    build: 
      context: ./int_db/
      dockerfile: int_db/Dockerfile
    ports:
      - "8082:80"
    networks:
      - calc_net

  # Base de données MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calc
    ports:
      - "3306:3306"
    networks:
      - calc_net

  # Serveur Minio
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - calc_net

  # Bucket S3 pour Minio
  bucket_s3:
    image: minio/mc
    entrypoint: mc
    command: mb s3/minio
    depends_on:
      - minio
    networks:
      - calc_net

networks:
  calc_net:
    driver: bridge

volumes:
  minio_data: